version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_app
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: "redis:alpine"
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env

volumes:
  postgres_data: 
  pgadmin_data:
